openapi: 3.0.1
info:
  title: CeridianDemoAPI
  description: API Definition of CeridianDemoAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/ceridian
paths:
  /employees:
    get:
      responses:
        default:
          description: Default response
  /employee/details/{xref}:
    get:
      parameters:
      - name: xref
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /employee/contacts/{xref}:
    get:
      parameters:
      - name: xref
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /employee/addresses/{xref}:
    get:
      parameters:
      - name: xref
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /employee/properties/{xref}:
    get:
      parameters:
      - name: xref
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /employee/combine/{xref}:
    get:
      parameters:
      - name: xref
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
